create table if not exists public.faculty_records (
  id bigint generated by default as identity primary key,
  name text not null,
  semester text not null,
  rank text not null,
  status text not null check (status in ('Permanent', 'Lecturer')),
  field text not null check (field in ('Biochemistry', 'Applied Physics', 'Computer Science')),
  remarks text not null default '',
  created_at timestamptz not null default now()
);

create index if not exists faculty_records_name_idx on public.faculty_records (name);
